name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check files
        run: ls -la

      - name: Basic test
        run: echo "HTML project is working ✔"

      - name: Deploy message
        run: echo "Deploy step completed"
